import React from "react";
import Head from "next/head";
import Image from "next/image";

import { Impact } from "@components/HomePage/Impact";
import { Mission } from "@components/HomePage/Mission";
import { HowItWorks } from "@components/HomePage/HowItWorks";
import { Landing } from "@components/HomePage/Landing";
import { Demo } from "@components/HomePage/Demo";

import styled from "styled-components";

import {
  ImpactLeftGear,
  ImpactRightGear,
} from "components/common/landing-page/ImpactGraphics";
import {
  HowItWorksBg1,
  HowItWorksBg2,
} from "components/common/landing-page/HowItWorksGraphics";
import {
  DemoLeftGear,
  DemoRightGear,
} from "../components/common/landing-page/DemoGraphics";
const landingSplash = "/home/home-landing-graphic.svg";

/* Styling */
const Container = styled.div`
  width: 100%;
  & > div.landingGraphicWrapper {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 1024px;
    background-color: ${(props) => props.theme.colors.B10};
    z-index: -1;
  }

  & > div.impactLeftGearWrapper {
    position: absolute;
    top: 1024px;
    z-index: -1;
  }

  & > div.impactRightGearWrapper {
    position: absolute;
    top: 1225px;
    right: 0;
    z-index: -1;
  }

  & > div.howItWorksBg1Wrapper {
    position: absolute;
    top: 1800px;
    left: 0;
    right: 0;
    z-index: -1;
  }

  & > div.howItWorksBg2Wrapper {
    position: absolute;
    top: 2180px;
    z-index: -1;
  }

  & > div.demoLeftGearWrapper {
    position: absolute;
    top: 2700px;
    z-index: -1;
  }

  & > div.demoRightGearWrapper {
    position: absolute;
    top: 2330px;
    right: 0;
    z-index: -1;
  }
`;

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>UW Blueprint</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Container>
        <div className="landingGraphicWrapper">
          <Image src={landingSplash} layout="fill" objectFit="cover" />
        </div>
        <Landing />
        <div className="impactLeftGearWrapper">
          <ImpactLeftGear />
        </div>
        <div className="impactRightGearWrapper">
          <ImpactRightGear />
        </div>
        <Mission />
        <Impact />
        <div className="howItWorksBg1Wrapper">
          <HowItWorksBg1 />
        </div>
        <div className="howItWorksBg2Wrapper">
          <HowItWorksBg2 />
        </div>
        <HowItWorks />
        <div className="demoLeftGearWrapper">
          <DemoLeftGear />
        </div>
        <div className="demoRightGearWrapper">
          <DemoRightGear />
        </div>
        <Demo />
      </Container>
    </div>
  );
};

export default Home;
