import React from "react";
import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";

// import { Header, Main, Cards, Footer } from "@components/css";
const landingSplash = "/home/home-landing-graphic.svg";
const landingWave = "/home/home-landing-wave.svg";

/* Styling */
const Container = styled.div`
    width: 100vw;
    display: flex;
    flex-direction: column;
`;

const Section = styled.div`
    position: relative;
    margin: auto;
    box-sizing: border-box;
    overflow-x: hidden;
    width: 100%;
`;

const LandingSection = styled(Section)`
    height: 1200px;

    & > div.imageWrapper {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 1024px;
        background-color: ${(props) => props.theme.colors.B10};
        z-index: -1;
    }

    & > div.missionSection {
        // height: 270px;
        position: relative;
        display: flex;
        justify-content: center;

        & > div.imageWrapper {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 100%;
            z-index: -1;
        }
    }
`;

const LandingContent = styled.div`
    height: 100vh;
    min-height: 1024px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
`;

const LandingTitle = styled.h2`
    color: ${(props) => props.theme.colors.C00};
`;
const LandingText = styled.p`
    color: ${(props) => props.theme.colors.C00};
`;

const Home: React.FC = () => {
    return (
        <div>
            <Head>
                <title>UW Blueprint</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <Container>
                <LandingSection>
                    <div className="imageWrapper">
                        <Image
                            src={landingSplash}
                            layout="fill"
                            objectFit="cover"
                        />
                    </div>
                    <LandingContent>
                        <LandingTitle>uw blueprint</LandingTitle>
                        <LandingText>
                            tech for social good. built by students.
                        </LandingText>
                        {/* <HStack> */}
                        {/* <Button type="secondaryLight" to="/join">
                                See our work
                            </Button>
                            <Button type="secondaryLight" to="/join">
                                Join our team
                            </Button> * /}
                        {/* </HStack> */}
                    </LandingContent>
                    <div className="missionSection">
                        <div className="imageWrapper">
                            <Image
                                src={landingWave}
                                layout="fill"
                                objectFit="cover"
                            />
                        </div>
                        <p>
                            Blueprint strives to make technology accessible and
                            useful for those who create communities and promote
                            social good.{" "}
                        </p>
                    </div>
                </LandingSection>
                <Section></Section>
            </Container>
        </div>

        // <div
        //     style={{
        //         display: "flex",
        //         flexDirection: "column",
        //         minHeight: "100vh",
        //     }}
        // >
        //     <Header />
        //     <Main />
        //     <Cards />
        //     <Footer />
        // </div>
    );
};

export default Home;
