import React from "react";
import Head from "next/head";
import Image from "next/image";

import { Impact } from "@components/HomePage/Impact";
import { Mission } from "@components/HomePage/Mission";
import { HowItWorks } from "@components/HomePage/HowItWorks";
import { Landing } from "@components/HomePage/Landing";
import { Demo } from "@components/HomePage/Demo";

import styled from "styled-components";

const landingSplash = "/home/home-landing-graphic.svg";
const impactLeftGear = "/home/home-impact-left-gear.svg";
const impactRightGear = "/home/home-impact-right-gear.svg";
const howItWorksBg1 = "/home/home-how-it-works-bg1.svg";
const howItWorksBg2 = "/home/home-how-it-works-bg2.svg";
const demoLeftGear = "/home/home-demo-left-gear.svg";
const demoRightGear = "/home/home-demo-right-gear.svg";

/* Styling */
const Container = styled.div`
  width: 100%;
  & > div.landingGraphicWrapper {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 1024px;
    background-color: ${(props) => props.theme.colors.B10};
    z-index: -1;
  }

  & > div.impactLeftGearWrapper {
    position: absolute;
    top: 1024px;
    z-index: -1;
  }

  & > div.impactRightGearWrapper {
    position: absolute;
    top: 1225px;
    right: 0;
    z-index: -1;
  }

  & > div.howItWorksBg1Wrapper {
    position: absolute;
    top: 1850px;
    left: 0;
    right: 0;
    height: 75%;
    z-index: -1;
  }

  & > div.howItWorksBg2Wrapper {
    position: absolute;
    top: 2180px;
    left: 0;
    right: 0;
    height: 35%;
    z-index: -1;
  }

  & > div.demoLeftGearWrapper {
    position: absolute;
    top: 2700px;
    z-index: -1;
  }

  & > div.demoRightGearWrapper {
    position: absolute;
    top: 2330px;
    right: 0;
    z-index: -1;
  }
`;

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>UW Blueprint</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Container>
        <div className="landingGraphicWrapper">
          <Image src={landingSplash} layout="fill" objectFit="cover" />
        </div>
        <Landing />
        <div className="impactLeftGearWrapper">
          <Image src={impactLeftGear} height={1000} width={1381} />
        </div>
        <div className="impactRightGearWrapper">
          <Image src={impactRightGear} height={524} width={331} />
        </div>
        <Mission />
        <Impact />
        <div className="howItWorksBg1Wrapper">
          <Image src={howItWorksBg1} layout="fill" objectFit="cover" />
        </div>
        <div className="howItWorksBg2Wrapper">
          <Image src={howItWorksBg2} layout="fill" objectFit="cover" />
        </div>
        <HowItWorks />
        <div className="demoLeftGearWrapper">
          <Image src={demoLeftGear} height={167} width={574} />
        </div>
        <div className="demoRightGearWrapper">
          <Image src={demoRightGear} height={1000} width={1440} />
        </div>
        <Demo />
      </Container>
    </div>
  );
};

export default Home;
